# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Dfarmclient
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: DfarmclientMSP

        # ID to load the MSP definition as
        ID: DfarmclientMSP

        MSPDir: ../organizations/peerOrganizations/dfarmclient.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('DfarmclientMSP.admin', 'DfarmclientMSP.peer', 'DfarmclientMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('DfarmclientMSP.admin', 'DfarmclientMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('DfarmclientMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('DfarmclientMSP.peer')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.dfarmclient.com
              Port: 11051
