# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Kmadmin
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: KmadminMSP

        # ID to load the MSP definition as
        ID: KmadminMSP

        MSPDir: ../organizations/peerOrganizations/kmadmin.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('KmadminMSP.admin', 'KmadminMSP.peer', 'KmadminMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('KmadminMSP.admin', 'KmadminMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('KmadminMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('KmadminMSP.peer')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.kmadmin.com
              Port: 9031
